"use client";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, FileText, FolderKanban, Mail, Plus } from "lucide-react";
import { useAdminData } from "./store";
import { PageTitle, Status } from "./ui";

export default function Overview() {
  const data = useAdminData();
  const stats = [
    { title: "Projects", value: data.projects.length, note: `${data.projects.filter(p => p.status === "draft").length} drafts in progress`, href: "/admin/projects", icon: FolderKanban, surface: "var(--sky-50)" },
    { title: "Blog posts", value: data.posts.length, note: `${data.posts.filter(p => p.status === "published").length} published in preview`, href: "/admin/posts", icon: FileText, surface: "var(--pink-50)" },
    { title: "Unread messages", value: data.messages.filter(m => !m.read && !m.archived).length, note: "Sample inbox only", href: "/admin/messages", icon: Mail, surface: "var(--sun-50)" },
  ];
  const recent = [...data.projects.map(p => ({ ...p, type: "Project", href: "/admin/projects" })), ...data.posts.map(p => ({ ...p, type: "Post", href: "/admin/posts" }))].sort((a, b) => b.updated.localeCompare(a.updated)).slice(0, 5);
  return <>
    <PageTitle eyebrow="Your workspace" title="Welcome back, Hope." description="A little clarity for everything you’re creating. Here’s where things stand." action={<Link href="/admin/projects?new=1" className="admin-button"><Plus className="size-4" /> New project</Link>} />
    <section className="admin-welcome relative mb-7 overflow-hidden rounded-3xl border p-7 sm:p-9"><div className="relative z-10 max-w-lg"><p className="text-xs font-medium text-primary">MAKE YOUR NEXT MOVE</p><h2 className="mt-3 text-2xl font-semibold tracking-tight sm:text-3xl">Good work deserves a great story.</h2><p className="mt-3 text-sm leading-relaxed text-body">Turn your latest project into a case study, share something you learned, or give your profile a little attention.</p><Link href="/admin/posts?new=1" className="mt-6 inline-flex items-center gap-2 text-sm font-medium text-primary">Write something new <ArrowRight className="size-4" /></Link></div><div aria-hidden="true" className="pointer-events-none absolute -right-12 -top-12 size-72 rounded-full border-[48px] border-primary/5" /></section>
    <section aria-label="Workspace totals" className="mb-8 grid gap-4 md:grid-cols-3">{stats.map(({ title, value, note, href, icon: Icon, surface }) => <Link href={href} key={title} className="admin-panel group p-6 transition-colors hover:border-primary/40"><div className="flex items-center justify-between"><span style={{ background: surface }} className="flex size-10 items-center justify-center rounded-xl text-ink"><Icon className="size-5" /></span><ArrowUpRight className="size-4 text-muted-foreground group-hover:text-primary" /></div><p className="mt-5 text-3xl font-semibold tracking-tight">{value}</p><p className="mt-1 text-sm font-medium">{title}</p><p className="mt-2 text-xs text-muted-foreground">{note}</p></Link>)}</section>
    <div className="grid gap-6 xl:grid-cols-[1.6fr_1fr]"><section className="admin-panel overflow-hidden"><div className="flex items-center justify-between border-b p-6"><h2 className="text-base font-semibold">Content at a glance</h2><span className="text-xs text-muted-foreground">Browser preview</span></div>{recent.map(item => <Link key={`${item.type}-${item.id}`} href={item.href} className="flex flex-wrap items-center justify-between gap-3 border-b p-5 last:border-0 hover:bg-muted/40"><div className="min-w-0"><p className="text-sm font-medium">{item.title}</p><p className="mt-1 text-xs text-muted-foreground">{item.type} · {item.updated ? `Updated ${new Date(item.updated).toLocaleDateString()}` : "Imported from portfolio"}</p></div><Status published={item.status === "published"} /></Link>)}</section><section className="admin-panel p-6"><p className="text-xs font-medium uppercase tracking-widest text-muted-foreground">A little housekeeping</p><h2 className="mt-3 text-xl font-semibold tracking-tight">Keep your story current.</h2><div className="mt-6 space-y-5">{[{ text: "Review your projects", sub: "Polish descriptions and case studies", href: "/admin/projects" }, { text: "Update your profile", sub: "Links, location, bio, and résumé", href: "/admin/settings" }, { text: "Explore the inbox", sub: "Try the sample message workflow", href: "/admin/messages" }].map((item, index) => <Link key={item.href} href={item.href} className="flex items-start gap-3"><span className="flex size-7 shrink-0 items-center justify-center rounded-full border text-xs text-primary">0{index + 1}</span><div><p className="text-sm font-medium hover:text-primary">{item.text}</p><p className="mt-1 text-xs text-muted-foreground">{item.sub}</p></div></Link>)}</div></section></div>
  </>;
}
